communes_coord = [
      
             {"name":"Hinche",            "lat": 19.15,         "lng": -72.01667,    "Departement": "Centre",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Cerca Carvajal",    "lat": 19.250,        "lng": -71.950,      "Departement": "Centre",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Cerca La Source",   "lat": 19.1667,       "lng": -71.7833,     "Departement": "Centre",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Fort-Liberté",      "lat": 19.6667,       "lng": -71.8333,     "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Perches",           "lat": 19.52305870,   "lng": -71.92383200, "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Ferrier",           "lat": 19.617,        "lng": -71.783,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},   
             {"name":"Ouanaminthe",       "lat": 19.54807,      "lng": -71.72397,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Mont-Organisé",     "lat": 19.367,        "lng": -71.783,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Trou du Nord",      "lat": 19.63333,      "lng": -72.01667,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Vallières",         "lat": 19.43548,      "lng": -71.92094,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Terrier Rouge",     "lat": 19.600,        "lng": -71.917,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Caracol",           "lat": 19.691,        "lng": -72.016,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Carice",            "lat": 19.350,        "lng": -71.817,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Capotille",         "lat": 19.433,        "lng": -71.717,      "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Sainte Suzanne",    "lat": 19.58333,      "lng": -72.08333,    "Departement": "Nord-Est",         "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Les Cayes",         "lat": 18.19331,      "lng": -73.74601,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Camp-Perrin",       "lat": 18.317,        "lng": -73.867,      "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Chantal",           "lat": 18.20269,      "lng": -73.88891,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Torbeck",           "lat": 18.1657547,    "lng": -73.8139579,  "Departement": "Sud",              "cocreation": True, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Chardonnières",     "lat": 18.26667,      "lng": -74.16667,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Port-à-Piment",     "lat": 18.25000,      "lng": -74.10000,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Roche à Bâteau",    "lat": 18.18333,      "lng": -74.00000,    "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Port-Salut",        "lat": 18.13333,      "lng": -73.9,        "Departement": "Sud",              "cocreation": True, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Arniquet",          "lat": 18.146,        "lng": -73.875,      "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Saint Jean du Sud", "lat": 18.083,        "lng": -73.850,      "Departement": "Sud",              "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Côteaux",           "lat": 18.2072607,    "lng": -74.040294,      "Departement": "Sud",           "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Acul du Nord",      "lat": 19.6808413-0.041, "lng": -72.317793,   "Departement": "Nord",          "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Plaine du Nord",    "lat": 19.68333,      "lng": -72.26667,    "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Limonade",          "lat": 19.66667,      "lng": -72.11667,    "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Saint-Raphaël",     "lat": 19.43917,      "lng": -72.19972,    "Departement": "Nord",             "cocreation": True, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Quartier Morin",    "lat": 19.667+0.03,        "lng": -72.167,      "Departement": "Nord",        "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
             {"name":"Ranquitte",         "lat": 19.4129673,    "lng": -72.0808875,  "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"Pignon",            "lat": 19.317,        "lng": -72.083,      "Departement": "Nord",             "cocreation": False, "nb_cocreation":0, "mou_signed": 0,}, 
             {"name":"La Victoire",       "lat": 19.3352998,    "lng": -72.0216309,             "Departement": "Nord",  "cocreation": False, "nb_cocreation":0, "mou_signed": 0,},
         ]